### ISSUE TITLE
Unclear intent of mappings

### ISSUE THREAD

**Issue by ticky** [gabomdq/SDL_GameControllerDB#118]
I’ve been doing some more digging into support for the newer Xbox Wireless Controller on macOS, and a patch recently landed in SDL2 itself adding support, and a mapping, for it (albeit with the new GUID format mentioned in #110)

This now makes me wonder, is this database intended to _include_ or _enhance_ the built-in mappings? Is it intended that support be maintained to add mapping support to older versions of SDL?

**Comment by gabomdq** [comment]
This database is meant as a quick way to share mappings with others, easy to edit and update. SDL's internal mappings require a new binary to be updated, which can be a fairly involved process on some systems, and also Sam requires that the mappings shipped with SDL are "verified" (whatever that means).

**Comment by ticky** [comment]
Given my fiancée and I have managed to land patches in SDL itself for some controller mappings, it doesn’t seem that high a bar! 😜 I can understand if this is where more obscure controller mappings go, though.

Is the intent that equivalents to mappings included in SDL itself be added here as well for backwards compatibility? What’s the intent if backwards compatibility isn’t possible for a given mapping?

**Comment by gabomdq** [comment]
Proper support for the Xbox controllers in all platforms is important, that's why the patches got accepted quickly :) In the particular case of your changes, since you added functionality to OSX HID code, there's no way the mapping would work correctly if you try to use it with a previous version of SDL. We can add them here, but the triggers won't work correctly....and to fix that you have to update SDL, which again makes adding them here pointless.

**Comment by ticky** [comment]
Right, but I guess my question is whether “the buttons map and can be used, but the triggers don’t do anything” is more desirable to you than “this controller doesn’t work at all?”
