### ISSUE TITLE
PSA : Updated fork

### ISSUE THREAD

**Issue by p-groarke** [gabomdq/SDL_GameControllerDB#156]
Since the project is inactive, I've been through all pull requests and have merged pretty much everything. I've also added some new automated checks (check for platform, check for duplicates).

https://github.com/p-groarke/SDL_GameControllerDB

Please send pull requests with new controller entries!

The 2.0.4 GUID version is released here https://github.com/p-groarke/SDL_GameControllerDB/releases/tag/2.0.4

**Comment by balthamos** [comment]
Well, guess I should have looked here first. I saw your fork had a lot of stuff, but I couldn't tell where you pulled the commits from.

I ended up doing the same thing as you, basically, except I merged everything so you can tell where something came from more readily. Also did a lot of cleaning on the mappings themselves, removing duplicates and whatnot.

We should try to consolidate our efforts...

**Comment by ticky** [comment]
As far as consolidation, it might make sense for this to be a community effort under an organisation so multiple people can evaluate and merge?

**Comment by p-groarke** [comment]
I consider my branch more as an "unstable" channel, if you wish to subscribe to settings that aren't as tested as the main db. The organisation is SDL and this project is the official db. You can merge/cherry-pick as you please obviously.

**Comment by balthamos** [comment]
Perhaps establishing and organization makes sense here. There isn't much we can do to test and evaluate other than check the quality of the code. We don't know if the actual mappings work or not unless one of us happens to have the exact hardware/software combination being added/changed. But, having an org will let ownership float, making the baton easier to pass.

The goal I'm seeking is a single repository people can go grab to get the maximal controller support for SDL2. If there are issues with the mappings, then those will be caught by the users, fixed by the devs, and the pushed back up to the main repo. It's a simple model, and if everyone plays by the rules, then everyone will benefit from a solid base of mappings.

Most mappings should be additions, so there won't be any conflicts. For updates to existing mappings, that's when we should exercise caution and work with the dev to figure out what changes were made and why, then react accordingly.

As it is now, there are least 30 different forks, most of which could have been pushed back to main without issue (other than merge conflicts due to the flat text file structure). With everything so fragmented, that makes it difficult for devs to pick the "right" repo, and in the extreme cases will scare them away as they go directly to their users to build their own set of mappings (which I've seen happen before). All the information becomes silo'd.

IMO, there isn't a reason to have stable/unstable branches for this project, because either:

1. Devs pick the stable branch out of fear, everything is fine, but unstable branch never gets tested
2. Devs pick the stable branch, get complaints from users that something doesn't work, switch to the unstable branch, and everything works great (and since everything is fine, they aren't motivated to provide any feedback)
3. Devs pick the unstable branch, get complaints/praise from the users that something doesn't/does work, and (hopefully) push that information back up

I would like to have option 3 be the preferred option because that gives us the most testing surface area. In that case, there is no reason to have a stable branch because it should never be targeted.

To deal with instability during the development phase and/or batch up changes, you would have releases that you tag every now and then. Should anything break, now there are revisions to roll back to and help pinpoint issues.

**Comment by blitz-research** [comment]
Nice work p-groarke, I will be using this DB in my project.

Is this 'official' repos here dead or something? Is there any point making pull requests to it?

If so, shouldn't current SDL2 wiki be linking to something like p-groake's repos instead? Assuming he/she is taking pull requests - are you?

> IMO, there isn't a reason to have stable/unstable branches for this project, because either:

I agree. IMO it's more important that someone's controller has at least a *chance* or working than just not being available at all.

**Comment by p-groarke** [comment]
@blitz-research I am *absolutely* taking PRs! You can send one here as well if you wish, maybe the owner of the repo will resurface?

My view on unstable/stable has changed. I view it more as keeping things alive while this repo is dormant :) With more tests and on releases (SDL 2.0.4, 2.0.5 +) for other engines/libraries.

**Comment by blitz-research** [comment]
Well, I did a have a new mapping, but it's already in your version!
