### ISSUE TITLE
consider consolidating data for dpad-only maps and clarifying mapping them in readme

### ISSUE THREAD

**Issue by offalynne** [gabomdq/SDL_GameControllerDB#260]
the great majority of dpad-only devices reflect input on the first two axes instead of POV or buttons. while the new sdl map format does accomodate axis directions on buttons via modifiers (ie: ‘dpadleft:-a0’) and this would presumably be how people would tend to follow the mapping configurator prompts, data in the db is inconsistent.

i’d argue that it’s actually more useful to follow the lead of the device concensus and map such dpads to ‘leftx’ and ‘lefty’ (again, only in cases where there are no analogue sticks and the device reflects dpad input via axes), both because of better backward compatibility for the maps, and because it is generally most useful in most applications to have directional axes input as opposed to xinput-dpad/pov-hat type input.

most of the applicable maps (presumably created on an older version of the spec) in the db are already laid out this way, but a few do use direction modifiers to map axes to the ‘dpad[..]’ keys.

regardless of which way is deemed “correct”, perhaps the linting process could identify these cases and unify the format

**Comment by p-groarke** [comment]
A couple things first. Data in the db will always be inconsistent, due to the nature of the db. For "perfect" mappings, you'd want to use the ones provided with SDL. Those are official mappings that are vouched by the SDL project.

This doesn't mean we can't make things better though.

The "correct" thing to do here is map dpads to hats. The db isn't for end-user consumption (even though that might happen with a niche power-user audience), it is for developers. When using this db, you *must* provide remapping functionalities in your game. See first paragraph why ;)

If you want to cleanup the db, feel free to open a PR. I would recommend to start small with one mapping, in case it doesn't go through review. I wouldn't want you to waste a bunch of time.

**Comment by p-groarke** [comment]
Hey @offalynne , are you OK if I close this issue?

**Comment by offalynne** [comment]
yep
