### ISSUE TITLE
Guidelines for mapping joystick controllers?

### ISSUE THREAD

**Issue by AliceLR** [gabomdq/SDL_GameControllerDB#272]
I came across a [Logitech WingMan Force 3D](https://i.imgur.com/xgyrOvx.png) joystick that isn't in the database and I'm not sure I've mapped it correctly. It has one non-analog "trigger" button, a hat and four buttons on the top of the stick, two buttons on the base, two standard joystick axes, a rotation axis, and a throttle axis. Are there guidelines for mapping joysticks like this, or should they even be here?

**Comment by offalynne** [comment]
sdl2 spec is a bit ambiguous: https://wiki.libsdl.org/CategoryGameController
there are definitely flightsticks already in this community db, though personally i don’t think it’s appropriate since the mapping functionality is explicitly for gamepads, joystick features really don’t map to xb360 equivelants, and the broader joystick api covers them fine

**Comment by p-groarke** [comment]
Yeah the db is really for gamepads, not joystick. For those, you'd use different APIs underneath the hood. Some mappings have slipped through though (and arcade sticks are OK as they map 1 : 1).

**Comment by AliceLR** [comment]
Alright, thanks. It looks like there are VID/PID lists in SDL_joystick.c for joysticks and throttles, so I'll see about adding it there.
