### ISSUE TITLE
Esperanza EG102

### ISSUE THREAD

**Issue by eugeneloza** [gabomdq/SDL_GameControllerDB#278]
Detected as:
_Debian Linux x64_:
Joystick name: **Microntek**              USB Joystick          

_Windows 7x64_:
Joystick name: **Microsoft PC-joystick driver**

Joystick axes: 6
Joystick buttons: 12
Joystick caps: 19

![Esperanza_analog](https://user-images.githubusercontent.com/10726162/66208714-70135280-e6be-11e9-8983-a616c5662bdf.jpg)
![Esperanza_digital](https://user-images.githubusercontent.com/10726162/66208715-70135280-e6be-11e9-834c-c735c2e19584.jpg)

Unfortunately I couldn't find any other place to report my joystick layout so reporting here. Note, the database already contains information for Microntek joystick, but the information doesn't cover all axes and buttons.

**Comment by offalynne** [comment]
shame about the guid conflict, thanks for reporting on it. it’s tricky with these cases bc the conflict is often between low-usage 3rd party controllers.. if there was an obvious way to determine relative market share at least it would help in deciding which map to keep and which to toss in case of conflicts like this. in any case the data is good to have in case SDL update the GUID format in the future. the similar retroarch autoconfig project scores devices on a combo of vid/pid and device name which sometimes (but not always) is better than the SDL method at disambiguating. 

would you mind posting a dump from lsusb please @eugeneloza ?

the issue should prob. be closed since it can’t meaningfully be addressed by this project, but the data is indeed good to retain for potential future application.

**Comment by offalynne** [comment]
can you provide a map using the tools in the readme please? :-)

**Comment by eugeneloza** [comment]
Oh, now I get it. Thanks!

Linux:
```
03000000790000000600000010010000,Microntek USB Joystick,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Linux,
```

**Comment by eugeneloza** [comment]
Windows 7
```
03000000790000000600000000000000,G-Shark GS-GP702,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,-rightx:+a2,righty:+a3,lefttrigger:b6,righttrigger:b7,
```
However, somehow the right stick could not detect movements right and down (On Linux everything works falwlessly). Let me try native gamepad driver.

**Comment by eugeneloza** [comment]
Analyzed record for G-Shark GS-GP702 and only now found out that I can press sticks too :D - I skipped it. I'll update the mapping soon.

**Comment by offalynne** [comment]
Since the GUID on Windows matches G-Shark you don’t need to bother actually, those maps come upstream from the SDL repo and so would be superseded anyway unless you want to make a PR there instead (which I wouldn’t bother with for that specific device regardless, for reasons I won’t get into here).

In any case thanks for the data you’ve provided here!

**Comment by eugeneloza** [comment]
> on Windows

No, I'm talking about Linux :) As I've said, Database already has a perfect mapping for my device in Windows.

**Comment by offalynne** [comment]
Unfortunately this data won’t be able to applied to this repo because it’s automatically drawn from SDL. If you want to take it upstream you can make a PR here instead: http://hg.libsdl.org/SDL. While your map does seem a good candidate as it’s a superset of what’s currently in the repo, there’s unfortunately a longstanding bug with this particular GUID that means it’d be better if it were blacklisted/removed from the db altogether unfortunately, see  https://bugzilla.libsdl.org/show_bug.cgi?id=4545

**Comment by eugeneloza** [comment]
Ah, I understand. No problem :) I think I'll close the issue then.
