### ISSUE TITLE
Better instructions for using SDL2 ControllerMap

### ISSUE THREAD

**Issue by akien-mga** [gabomdq/SDL_GameControllerDB#307]
The README references https://github.com/gabomdq/SDL_GameControllerDB#sdl2-controllermap as a utility that can be used on all supported platforms, but the target link goes to the SDL2 download page and AFAIK there's no prebuilt version of ControllerMap included.

From there it's not obvious to figure out how to get the utility to extract controller mappings.

More importantly, I'm looking into it to retrieve mappings for Android gamepads, and the SDL2 build instructions for Android don't seem to cover generating somehow a usable version of the `controllermap.c` test to deploy on a phone.

CC @NY00123 who added a mapping in the past and might know what the process would be.

Cf. godotengine/godot#12696.

**Comment by offalynne** [comment]
This DB is in service of development using SDL2, if it works in service of other software that is built on SDL2 or otherwise all the better, but support for building code from the SDL2 repo is out of scope here. If you need help building the Android utility app, you should look for support from the SDL2 project.

Here’s a direct link to the app in the SDL repo now (though it may well change location at a later date): https://hg.libsdl.org/SDL/file/1e585115ed86/test/controllermap.c

And instructions provided by the SDL2 project on building for Android: https://wiki.libsdl.org/Android

**Comment by akien-mga** [comment]
> This DB is in service of development using SDL2, if it works in service of other software that is built on SDL2 or otherwise all the better, but support for building code from the SDL2 repo is out of scope here.

Well my intent is to have Android mappings contributed to this repository to better the development of SDL2 (and incidentally other applications using those bindings). So if this repository is the prime location to contribute new bindings before upstreaming in SDL2, I think it makes sense to have it document the workflow as best as possible.

> And instructions provided by the SDL2 project on building for Android: https://wiki.libsdl.org/Android

Thanks, that seems good. I had looked at the `README-android.md` in the SDL2 repository but didn't think to look for more details in the wiki.
If I can extract a few easy steps to build `test/controllermap.c` specifically, I'll share them here.

**Comment by offalynne** [comment]
This DB is informal and downstream of SDL2. If you want to “better the development of SDL2”, better to contribute directly to that project.

**Comment by p-groarke** [comment]
@akien-mga Feel free to contribute the documentation to our readme, or a new md file. I personally don't know how SDL are gathering their android mappings.

Good day
