### ISSUE TITLE
Is SDL_GameControllerDB still maintained? AND WHAT HAPPENED SEVERAL HOURS EARLIER?

### ISSUE THREAD

**Issue by XenoAmess** [gabomdq/SDL_GameControllerDB#318]
![screenshot](https://user-images.githubusercontent.com/17455337/74581829-2f720100-4fef-11ea-95ba-30487553c5ba.png)
This image is taken when some hours ago I visit SDL_GameControllerDB on github.
It saids SDL_GameControllerDB is not maintained now and suggested using SDL_GameControllerDB2.
And when I go here now I see the readme is revoked.
And from my security scanner I see you force-push(and rebase) 8 hours ago right?

So I'm wondering about:
1. What happened exactly?
2. Why you rebase & push-f? 
3. What is the relationship between gabomdq/SDL_GameControllerDB and groarke/SDL_GameControllerDB2 in your opinion?
4. What shall I do now as a user, shall I use gabomdq/SDL_GameControllerDB or p-groarke/SDL_GameControllerDB2?

**Comment by offalynne** [comment]
Since August 2017 user p-groarke has near-exclusively been handling PRs and maintenance on this repo. Since it's unofficial and community maintained, seems reasonable that he's moved to a different repo in order to better administrate.

**Comment by XenoAmess** [comment]
> Since August 2017 user p-groarke has near-exclusively been handling PRs and maintenance on this repo. Since it's unofficial and community maintained, seems reasonable that he's moved to a different repo in order to better administrate.

I know what you said.
I've been watching this repo for a long time.
but you didn't answer my all 4 questions...

**Comment by gabomdq** [comment]
Hi! I'm Gabriel, I created this database and the SDL functionality that supports it (among many other SDL improvements). Due to other work related commitments, as it often happens with community supported projects, I was constantly running behind attending PRs and issues here. p-groarke at the time offered to help so I granted him contributor access and everything was fine for a few years, I felt like I left the project in good hands.
A couple days ago he requested admin permissions here, a request I denied since I didn't fully buy the reasons he cited for it, so he proceeded to push that commit you saw (without my knowledge nor consent, and betraying the trust I placed in  him), forcing me to remove the commit and remove his collaborator permissions.
This project will still be maintained, and as to what database you should use, that decision is up to you.
