### ISSUE TITLE
Steam Wireless Controller map

### ISSUE THREAD

**Issue by tsr8** [gabomdq/SDL_GameControllerDB#342]
Here you have mapping for Steam Wireless Controller (created with Gamepad Tool):
03000000de2800004211000011010000,Wireless Steam Controller,platform:Linux,a:b2,b:b3,x:b4,y:b5,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.8,dpdown:h0.2,dpleft:h0.12,dpright:h0.3,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b8,righttrigger:b9,

**Comment by gabomdq** [comment]
This looks different from the other mappings we have in the DB for the same controller.

**Comment by tsr8** [comment]
Thats why I post it here. Defaults works wrong with my controller.

**Comment by offalynne** [comment]
@tsr8 what method did you use to connect? i assume this map is produced by the new kernel driver? i can investigate/confirm on my end in a few weeks.

**Comment by tsr8** [comment]
Connected wirelessly by dongle.

Dnia 28 maja 2020 01:31:45 CEST, "alynne o." <notifications@github.com> napisał(a):
>@tsr8 what method did you use to connect? i assume this map is produced
>by the new kernel driver? i can investigate/confirm on my end in a few
>weeks.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabomdq/SDL_GameControllerDB/issues/342#issuecomment-634997968

-- T.

**Comment by offalynne** [comment]
Can confirm this map is correct with the Linux kernel driver (and will not interfere or conflict with the existing maps). I think for the sake of parity with the other maps the dpad should be mapped to left pad clicks instead of touches, but otherwise everything works correctly. A duplicate map is necessary with the GUID for wired mode. I'll author a PR with these shortly, thanks for reporting @tsr8
