### ISSUE TITLE
Sony DualShock 3 controllers incorrectly mapped by bad PR

### ISSUE THREAD

**Issue by offalynne** [gabomdq/SDL_GameControllerDB#366]
This PR broke official PS3 controllers: https://github.com/gabomdq/SDL_GameControllerDB/pull/363

The original map is correct for the vast majority of PS3 controller devices.

**Comment by gabomdq** [comment]
I don't have PS3 controllers to verify, @offalynne do you have this controller?

**Comment by offalynne** [comment]
Yes

**Comment by madmiraal** [comment]
@offalynne I'm curious to understand why the [original mapping](https://github.com/gabomdq/SDL_GameControllerDB/blob/71554c8d13acea52dc7dfeaaed069689c06f9721/gamecontrollerdb_204.txt#L67) that has existed since the [database was created](https://hg.libsdl.org/SDL/diff/172b0c6e51d6/src/joystick/SDL_gamecontrollerdb.h#l1.41) and works for people with older controllers is incorrect, and how the [current, significantly different mapping](https://github.com/gabomdq/SDL_GameControllerDB/blob/59067a003edf9eb70dbf580869deac17cfa04dce/gamecontrollerdb.txt#L226) is correct.

**Comment by offalynne** [comment]
Windows device drivers. The new mapping is provided by a device using the Sony-authored official Windows driver for the DualShock 3 that was only widely released with the release of the PlayStation Now client.
