### ISSUE TITLE
Right joystick up-down dosn't work

### ISSUE THREAD

**Issue by sunny-gg95** [gabomdq/SDL_GameControllerDB#467]
Idk but it work in rocket league and joytokey

https://user-images.githubusercontent.com/61912148/120414509-4a9f8600-c384-11eb-9bc6-1b4a4aebad5f.mp4

**Comment by offalynne** [comment]
There's not a map for the device in this DB because it's ubiquitous, generic and mapped differently depending on the model. See https://discourse.libsdl.org/t/duplicated-conflicting-guids-for-the-dragonrise-pc-twin-shock-controllers/24112/3

If you want to get a map working for your model locally, you can do so by mapping it yourself and setting an environment variable using the gamepad tool.
