### ISSUE TITLE
GameSir T4w Linux mapping has invalid `start` and `y` keys

### ISSUE THREAD

**Issue by akien-mga** [gabomdq/SDL_GameControllerDB#513]
The mapping was added in https://github.com/gabomdq/SDL_GameControllerDB/pull/509, but it has empty `start:` and `y:` keys:

```
03000000bc2000005656000011010000,Gamesir T4w,a:b0,b:b1,y:,x:b3,start:,guide:b12,back:b8,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,lefttrigger:b6,righttrigger:b7,leftstick:b10,rightstick:b11,rightx:a2,righty:a3,platform:Linux,
```

CC @mamin

**Comment by offalynne** [comment]
Thanks, been a minute since we've linted. inferred the missing values here https://github.com/gabomdq/SDL_GameControllerDB/commit/ebb90a7d27c9ce6bf258325dac7a54e40ac61330

Please confirm if you're able @mamin, and if possible please try to get an analogue mapping for the triggers as well (press lightly if you're using the mapping tool).

**Comment by offalynne** [comment]
https://github.com/gabomdq/SDL_GameControllerDB/commit/64869b063c3cc1e7fff2dbcb35a1f711a211dd21
