### ISSUE TITLE
Mapping for NSO Mega Drive/Genesis 3btn controller

### ISSUE THREAD

**Issue by nfp0** [gabomdq/SDL_GameControllerDB#546]
Here is the mapping for the Nintendo Switch Online Mega Drive/Genesis 3btn controller straight out of the Steam config file:

Linux:
`050000007e0500001720000001000000,dev:gen:Nintendo Switch Online Mega Drive/Genesis 3btn,platform:Linux,a:b1,b:b0,start:b9,guide:b12,back:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,righttrigger:b5`

Windows:
`030000007e0500001720000000000000,dev:xb1:Wireless Gamepad,platform:Windows,a:b1,b:b0,righttrigger:b5,guide:b12,back:b7,start:b9,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2`

I've followed the mapping from the README, with the exception of mapping the home button to Steam's "guide" button. Feel free to remove it if you find it best.
Mega Drive's "Mode" button is mapped to the "Back" button on the Xbox controller and I left the "Screenshot" button unmapped.

Careful, because the IDs conflict with the Nintendo Switch Online SNES controller.

**Comment by offalynne** [comment]
Thank you so much for following up @nfp0, I appreciate it !

**Comment by nfp0** [comment]
No problem!

**Comment by offalynne** [comment]
@PitiBatou would you be able to provide mappings for the Sega 6b and N64 on platforms available to you ?

**Comment by PitiBatou** [comment]
@offalynne just had a read through the project's README, this is awesome! I should be able to whip up profiles for Windows & Linux over the weekend. It seems the N64 Windows mapping is already in the db?

I think I can contribute some other stuff as well that I haven't seen in the database yet -- given enough time ;)

- Nintendo Switch Online Famicom Controllers (will probably show up as same as the NES ones?)
https://store-jp.nintendo.com/list/software/70010000000850.html
- NeoGeo X USB JoyStick Controller
https://www.youtube.com/watch?v=Rlg7r5RNwCY
- BigBig Won Elitist S Controller
- https://www.bigbigwon.com/product/controller/elitist-s/
- Hori Edge 301 PC Controller
https://hori.jp/products/edge_301/
- Hori Switch Battle Pad Controller (GC style USB controller)
https://hori.co.uk/battle-pad-zelda-for-nintendo-switch/
- MayFlash N64 Adapter (2 ports)
https://www.mayflash.com/product/showproduct.php?id=19
- MayFlash SNES Adapter (2 ports)
https://www.mayflash.com/product/showproduct.php?id=18
- Elecom GamePad Converter (single port Wii Classic Controller adapter)
https://www.elecom.co.jp/products/JC-W01UWH.html

**Comment by offalynne** [comment]
That would be a huge get, thank you ! 

> seems the N64 Windows mapping is already in the db

I authored it after your RA-AC contribution as the Windows GUIDs are simplified, feel free to check if it is working correctly, would appreciate it!

You can probably skip the Hori Battle Pad as I have one and have authored maps to cover it as well (it’s ID conflicts with other Hori Switch pads on some platforms), though feel free to confirm.

The NES style controllers I believe report as JoyCons, but again feel free to check in case they present unique GUIDs etc.

Rest sounds great !

**Comment by PitiBatou** [comment]
@offalynne 

Here is the code for the NSO N64 controller (Linux). The only difference with the Windows profile seems to be the GUID. Kindly note I added a mapping for button 12 (the Switch "screenshot" button) as "back".

`050000007e0500001920000001000000,Nintendo Switch N64 Controller,+rightx:b8,+righty:b2,-rightx:b3,-righty:b7,a:b1,b:b0,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,back:b13,leftshoulder:b4,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,righttrigger:b10,start:b9,platform:Linux,`

And the one for the MD/Gen 6B for both platforms. I mapped physical Z to LB and physical C to RB and MODE as RT. Let me know if this needs changing. Similar to the N64, I have the "screenshot button" b12 as "back".

`050000007e0500001720000001000000,Nintendo Switch MD/Gen 6B Control Pad,a:b1,b:b0,x:b6,y:b2,back:b13,guide:b12,start:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,righttrigger:b7,platform:Linux,`


`030000007e0500001720000000000000,Nintendo Switch Online MD/Gen 6B,a:b1,b:b0,x:b6,y:b2,back:b13,guide:b12,start:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,righttrigger:b7,platform:Windows,`

I'll get to my other controllers in the coming days. One question: what would be the mapping for Neo Geo (A.B,C,D as A,B,X,Y?). Thanks!

**Comment by PitiBatou** [comment]
@offalynne 

OK, turns out this went much quicker than I thought, owing to the fact that a lot of my controllers/adapters are already in the list (similar GUID).

The "BigBigWon Elitist-S" identifies as an Xbox 360 Controller. 

`030000005e0400008e02000010010000,Xbox 360 Controller,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftshoulder:b4,rightshoulder:b5,leftstick:b9,rightstick:b10,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:+a2,righttrigger:+a5,platform:Linux,
`

The Hori EDGE 301 identifies as "Generic Xbox pad".

`030000000d0f00006d00000020010000,Generic X-Box pad,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftshoulder:b4,rightshoulder:b5,leftstick:b9,rightstick:b10,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:+a2,righttrigger:+a5,platform:Linux,
`

What is the best practice here? Do you leave the description as Xbox 360 Controller/XInput pad or do you prefer the commercial name?

NeoGeox X Arcade Stick. That one was straightforward enough:

`0300000092120000474e000000010000,TOMMO NEOGEOX Arcade Stick,a:b0,b:b1,x:b3,y:b2,back:b8,start:b9,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,platform:Linux,`

Elecom JC-W01UWH "Wii Classic Controller to USB"

`030000006e0500000720000010010000,HuiJia  JC-W01U,a:b2,b:b3,x:b0,y:b1,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Linux,`

Another HuiJia chip, which are found in a number of USB adapters, including the many MayFlash.

Speaking of which, my two MayFlash adapters -- N64 and SNES (2ports) -- were both detected as "HuiJia  USB GamePad" with the GUID 030000008f0e00001330000010010000. This GUID is already in the DB with the "HuiJia SNES Controller" descriptor. The N64 analog joystick was seemingly not detected and in both cases only a single port actually registered any input. Probably safer to leave them out at this stage?

The batteries of my Famicom Classic controllers are flat, will update later this week together with the Windows GUID for the controllers in this post.

**Comment by offalynne** [comment]
Thank you ! I appreciate the thorough details — glad to contribute the necessary edits to the name field etc, not a worry !

**Comment by offalynne** [comment]
The XInput mappings are unnecessary and the rest are already in the DB so I’ll close this for now, feel free to open a new issue or PR if you have additional mapping data to provide. Thanks again!
