### ISSUE TITLE
Consider adding codespell github action to catch any typos before merging code

### ISSUE THREAD

**Issue by luzpaz** [gabomdq/SDL_GameControllerDB#601]
Avoid merging typos (see https://github.com/gabomdq/SDL_GameControllerDB/pulls?q=is%3Apr+author%3Aluzpaz+sort%3Aupdated-desc) 

See https://github.com/codespell-project/actions-codespell

**Comment by offalynne** [comment]
This is impractical since barely any of the db will ever pass spellcheck: it only applies to the description field, most brand and product names will false positive, and if the warning is consistently unhelpful, actual positive hits will be easily missed.

If you want to author a PR for a workflow configuration you think will work correctly and helpfully, I’ll consider it.

Thousands of maps maintained by two contributors (spellcheck or no) are bound to produce mistakes from time to time.

**Comment by luzpaz** [comment]
Example how to remove false positives and how the current repo cycled through `codespell` is handled;  
![Screenshot_20220721_142226](https://user-images.githubusercontent.com/4140247/180286341-25c60943-d2cc-4226-a1b5-878e1c87b656.png)
