### ISSUE TITLE
Questions about specific bindings types.

### ISSUE THREAD

**Issue by Donatello-za** [gabomdq/SDL_GameControllerDB#607]
If someone can point me to the docs where I can read what these bindings mean I'd greatly appreciate it. Sorry for asking about it here.

* `+a0` and `-a0`: From forum posts I understand this is simply the direction of the axis, meaning the binding only applies in the particular positive or negative direction?
* `a0~` to `a5~`: From forum posts these seem to be "inverted axis". Is this correct?
* `h0.1, h0.2, h0.4, h0.8`: These are for "hats" I think, but what does the `0.x` section mean? If these are 4 directions, what about hats with 8 directions?

Last question: Why are there gaps between button indexes: For example, from buttons `b33` there are gaps between the button index numbers up to `b161`. My guess is that some devices simply report the button indexes like that?

Thanks in advance!

**Comment by offalynne** [comment]
Suggest you take these question to the [SDL2 forum](https://discourse.libsdl.org/).

**Comment by Donatello-za** [comment]
> Suggest you take these question to the [SDL2 forum](https://discourse.libsdl.org/).

Thanks @offalynne

**Comment by offalynne** [comment]
Here are answers from my (limited) knowledge:

1. yes
2. yes
3. for POV hat mapping `x.y`: x is the hat index, (same as button or axis index), y is a bitmask. i believe the latter is per HID spec. so in the implementation, 8 direction hats work fine, because there are only 4 underlying switches anyway, so diagonals can be derived using the other 4 values.

**Comment by Donatello-za** [comment]
Thank you for taking the time to answer my questions! I haven't yet had time to ask on the SDL2 forums but this will do 100% for now.
