### ISSUE TITLE
Potentially incomplete DPad Entries

### ISSUE THREAD

**Issue by sqldatabunny** [gabomdq/SDL_GameControllerDB#672]
I found three records in the database that appear to have dpup but not dpdown recorded for them and another that has dpdown but not dpup. I guess I'm not sure that these are incorrect but, from what I can tell, it does seem like these should all have four DPad buttons. I thought that it would be worth mentioning them in case these are mistakes.

The following may be missing dpdown:
* Mayflash F101 (03000000242f00003700000000000000)
* Huperkin N64 Adapter (31306635363562663834633739396333)
* Hyperkin N64 Adapter (5368616e57616e202020202048797065)

The following may be missing dpup:
* Sony Vita (63376637643462343766333462383235)

There are no similar instances for dpleft and dpright, for the record. I apologize if this issue is erroneous.

**Comment by offalynne** [comment]
F101 is an easy fix, https://github.com/gabomdq/SDL_GameControllerDB/commit/674e0817496ba17402acf7e3dec661fd0a043b81

As for the others, I ***believe*** those mappings are mine: in my findings to memory some devices indeed seem not to properly register all 4 dpad buttons on devices in SDL for Android.

The difficult question then is whether it is worthwhile to map any dpad direction at all since it will leave at least one dpad axis broken/useless as a directional input.

I will double check with these devices when I am able to confirm.
