### ISSUE TITLE
Mapping for Xbox Elite detected as Bluetooth LE XINPUT compatible input 

### ISSUE THREAD

**Issue by noidexe** [gabomdq/SDL_GameControllerDB#699]
The Xbox Elite gamepads are currently being detected as an extra "Bluetooth LE XINPUT compatible input" when connected via bluetooth. See report here: https://answers.microsoft.com/en-us/windows/forum/all/xbox-one-controller-identified-as-bluetooth-le/f6aae298-fd84-4125-8568-137b15121f20

This are the correct mappings for windows: 
030000005e040000220b000000000000,Bluetooth LE XINPUT compatible input device,platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:+a2,righttrigger:-a2,

**Comment by offalynne** [comment]
@noidexe Thanks. Can you check with the Windows game controller dialogue (`joy.cpl` from Command Prompt, Run, or Start) if you get a button value result for the triggers ? Ideally if you could post a screenshot that would be appreciated. The trigger axes are an issue with DInput since both triggers map to the same axis, so this mapping works when they are pressed independently not together. The button result may not be analogue but at least it's technically correct, at least until MS deigns to fix their own issues with the controller firmware or XInput driver.

**Comment by noidexe** [comment]
It seems there's no button input. Right trigger substract and Left trigger adds to the Z axis, and you're right. If you use they together they're added together :/

Here are some screenshots:

Left trigger fully depressed
![image](https://github.com/gabomdq/SDL_GameControllerDB/assets/526829/1914a2b6-144c-476b-88ac-fc9acbb25236)

Right trigger fully depressed
![image](https://github.com/gabomdq/SDL_GameControllerDB/assets/526829/45e6078c-cceb-407e-90fc-fde8598dad55)

I tried changing the trigger stops just in case it changed how the input was handled but it still uses the z axis

To clarify. They still appear as regular xinput controller that works just fine, the problem is that they also appear as a second gamepad. 

![image](https://github.com/gabomdq/SDL_GameControllerDB/assets/526829/fdb437e6-1552-4c7d-a199-efd54b51f2f4)

I noticed the same in Godot which AFAIK only uses the mapping db and not the library so I assume it's not something SDL specific but rather windows exposing two gamepads

**Comment by offalynne** [comment]
Thanks for following up. This circumstance does not call for a mapping so much as blacklisting the DInput device on upstream software in deference to the XInput device. Ideally MS would fix the root issue but in the meantime, it should be taken up directly with the Godot and/or SDL projects.
